spring.application.name=uniqlm

# Heroku dynamic port
server.port=${PORT:9090}

# REQUIRED FOR HEROKU: Trust the X-Forwarded-Proto header so Spring knows the app is running on HTTPS
server.forward-headers-strategy=native

# Force cookies for session tracking
server.servlet.session.tracking-modes=COOKIE

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://c7b4i1efuvdata.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/devs11nognt8i2
spring.datasource.username=u4dj57ncuk96lr
spring.datasource.password=pc8496e1b926ad546e767f736796aa074c539a90ade198c445cbfb46004ab1b2a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= GOOGLE OAUTH =================
spring.security.oauth2.client.registration.google.client-id=44020061202-g1k609qe6ul5m5n8arvcs6rqbghjn027.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# This MUST match what you put in Google Cloud Console exactly
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uniqlm@uniqlm.com
spring.mail.password=tgpw shgi pkqs wsuc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ================= APP REDIRECTS =================
# Set FRONTEND_URL as an environment variable in Heroku to https://uniqlm.com
app.frontend.url=${FRONTEND_URL:https://uniqlm.com}

app.reset-password-url=${app.frontend.url}/reset-password
app.verify-email-url=${app.frontend.url}/verify-email

# Path on your frontend where the token will be processed
app.oauth2.redirect-path=/home

# ================= SWAGGER =================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs